sudo: required

language: go

services:
  - docker

before_script:
  - docker login --username=otobrglez --email=otobrglez@gmail.com -p $DOCKER_PASS
  - docker build -t otobrglez/rss-machine -f Dockerfile .

script:
  - go test -v ./...
  - docker run -ti -p 127.0.0.1:5000:5000 -d otobrglez/rss-machine && sleep 3
  - curl -s --retry 3 --retry-delay 5 -v "http://127.0.0.1:5000/parse?url=http://rss.cnn.com/rss/edition.rss"

after_success:
  - export REPO=otobrglez/rss-machine
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker push $REPO
