sudo: required

language: go

services:
  - docker

before_script:
  - docker login --username=otobrglez --email=otobrglez@gmail.com -p $DOCKER_PASS
  - docker build -t otobrglez/rss-machine -f Dockerfile .

after_success:
  - export REPO=otobrglez/rss-machine
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
